# Generated by Django 4.0.4 on 2022-05-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labID', models.CharField(max_length=30)),
                ('date', models.DateField(verbose_name='%m/%d/%Y')),
                ('type', models.CharField(max_length=10)),
                ('problem', models.CharField(max_length=1500)),
            ],
            options={
                'verbose_name': 'reports',
            },
        ),
    ]
