# Generated by Django 4.0.4 on 2022-05-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'report'},
        ),
    ]
