# Generated by Django 4.0.4 on 2022-05-25 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0003_lab_buildingnum_lab_capacity_lab_floornum_lab_labid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'verbose_name': 'Laboratorie'},
        ),
    ]
