# Generated by Django 4.0.4 on 2022-05-25 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0004_alter_lab_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lab',
            new_name='LabInfo',
        ),
    ]
