# Generated by Django 4.0.4 on 2022-05-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0005_rename_lab_labinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='labId',
            field=models.CharField(default='hoba', max_length=30),
        ),
        migrations.AlterField(
            model_name='labinfo',
            name='labName',
            field=models.CharField(default='hoba', max_length=30),
        ),
    ]
