# Generated by Django 4.0.4 on 2022-05-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0006_alter_labinfo_labid_alter_labinfo_labname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labinfo',
            old_name='buildingNum',
            new_name='buildingNumber',
        ),
        migrations.RenameField(
            model_name='labinfo',
            old_name='floorNum',
            new_name='floorNumber',
        ),
        migrations.RenameField(
            model_name='labinfo',
            old_name='labId',
            new_name='labID',
        ),
    ]
