# Generated by Django 4.0.4 on 2022-05-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0007_rename_buildingnum_labinfo_buildingnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labinfo',
            name='buildingNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
