# Generated by Django 4.0.4 on 2022-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='first name', max_length=30)),
                ('lastName', models.CharField(default='last name', max_length=30)),
                ('email', models.CharField(default='email', max_length=50)),
                ('password', models.CharField(default='password', max_length=50)),
            ],
            options={
                'verbose_name': 'User',
            },
        ),
    ]
