# Generated by Django 4.0.4 on 2022-05-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_alter_signup_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'costumer'},
        ),
    ]
