# Generated by Django 4.0.4 on 2022-05-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_alter_signup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='firstName',
            field=models.CharField(default='first name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lastName',
            field=models.CharField(default='last name', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='password1', max_length=50, null=True),
        ),
    ]
