# Generated by Django 4.0.4 on 2022-05-25 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_alter_signup_email_alter_signup_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
