# Generated by Django 4.0.4 on 2022-05-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_alter_signup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'costumer'},
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='firstName',
            field=models.CharField(default='firstName', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='lastName',
            field=models.CharField(default='lastName', max_length=30),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(default='password1', max_length=50),
        ),
    ]
