# Generated by Django 4.0.4 on 2022-05-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0006_alter_signup_options_alter_signup_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
