# Generated by Django 4.0.4 on 2022-05-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0007_alter_signup_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'costumer'},
        ),
    ]
